......

diff --git a/install_controller b/install_controller
--- a/install_controller
+++ b/install_controller
@@ -40,40 +40,11 @@ for IP in $HOST_IPS; do
             HOST_IP=$IP
             break;
         fi
-    done
-    if [ "$HOST_IP" == "" ]; then
-        echo "Could not determine host ip address."
-        exit 1
+done
+if [ "$HOST_IP" == "" ]; then
+    echo "Could not determine host ip address."
+    exit 1
 fi
-
-#install monitor related package and start services
-cd $TOP_DIR
-cd kanyun/
-cat <<EOF >kanyun.conf
-[server]
-host: *
-port: 5551
-
-[mysql_db]
-host:127.0.0.1
-user:root
-passwd:$PASSWORD
-db:monitor
-cache_server:localhost
-cache_time_buffer:144000
-
-[worker]
-id: worker_$(hostname)
-worker_timeout: 60
-dataserver_host: 127.0.0.1
-dataserver_port: 5551
-log: /tmp/kanyun-worker.log
-EOF
-sudo ps ax|grep -v grep|grep kanyun-|awk '{print $1}'|xargs -L 1 kill -9
-sudo apt-get -y install libzmq-dev python-setuptools python-mysqldb redis-server python-redis python-zmq
-nohup ./kanyun-server > .kanyun-server.nohup&
-nohup ./kanyun-worker >.kanyun-worker.nohup &
-cd ..
 
 #get available space
 cd $TOP_DIR
@@ -102,4 +73,35 @@ VOLUME_BACKING_FILE_SIZE=$back_file_size
 IMAGE_URLS=http://stackops.s3.amazonaws.com/images/centos-6.2-x86_64.img.tar.gz
 EOF
 ./stack.sh
+
+#install monitor related package and start services
+cd $TOP_DIR
+cd kanyun/
+su -c "cat <<EOF >kanyun.conf
+[server]
+host: *
+port: 5551
+
+[mysql_db]
+host:127.0.0.1
+user:root
+passwd:$PASSWORD
+db:monitor
+cache_server:localhost
+cache_time_buffer:144000
+
+[worker]
+id: worker_$(hostname)
+worker_timeout: 60
+dataserver_host: 127.0.0.1
+dataserver_port: 5551
+log: /tmp/kanyun-worker.log
+EOF" stack
+sudo mysql -uroot -pcsdb123cnic -e 'DROP DATABASE IF EXISTS monitor;'
+sudo mysql -uroot -pcsdb123cnic -e 'CREATE DATABASE monitor CHARACTER SET utf8;'
+sudo mysql -uroot -pcsdb123cnic -e 'use monitor;source vm_monitor.sql;'
+sudo ps ax|grep -v grep|grep kanyun-|awk '{print $1}'|xargs -L 1 kill -9 1>/dev/null 2>&1
+sudo apt-get -y install libzmq-dev python-setuptools python-mysqldb redis-server python-redis python-zmq 1>/dev/null 2>&1
+su -c "nohup ./kanyun-server > .kanyun-server.nohup 2>/dev/null&" stack
+su -c "nohup ./kanyun-worker > .kanyun-worker.nohup 2>/dev/null&" stack
 
